import { existsSync } from "node:fs";
import { defineConfig, type Plugin } from "vite";
import { resolve } from "node:path";

/**
 * `public/nami-shah-cv.pdf` is regenerated by `npm run pdf` (which also
 * writes the same file to `dist/` for production). Vite serves anything in
 * `public/` as-is with correct headers, so once that's been run, the
 * "Download CV" link just works in `vite dev` too, no plugin needed.
 *
 * This plugin only exists as a safety net for the *first* time a
 * contributor runs `vite dev` before ever running `npm run pdf`: without
 * it, requesting a path with no matching file falls through to Vite's SPA
 * fallback, which quietly serves `index.html` (200 OK) for `/nami-shah-cv.pdf`
 * too, silently downloading an HTML file with a misleading confirmation
 * instead of a clear error. Dev-only: never runs during `vite build`/`preview`.
 */
function devPdfFallbackPlugin(): Plugin {
  return {
    name: "dev-pdf-fallback",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url !== "/nami-shah-cv.pdf" || existsSync(resolve("public/nami-shah-cv.pdf"))) return next();
        res.statusCode = 404;
        res.setHeader("Content-Type", "text/plain");
        res.end("No PDF yet - run `npm run pdf` first (needs `npm run build` beforehand), then reload.");
      });
    },
  };
}

export default defineConfig({
  base: "/",
  plugins: [devPdfFallbackPlugin()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        cv: resolve(__dirname, "cv.html"),
      },
    },
  },
});
