import { chromium } from "playwright";
import { preview } from "vite";
import { resolve } from "node:path";
import { writeFile } from "node:fs/promises";

const server = await preview({ preview: { port: 4173, strictPort: true } });
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto("http://localhost:4173/cv.html", { waitUntil: "networkidle" });
const pdf = await page.pdf({ format: "A4", printBackground: true });
await browser.close();
await server.close();

// Also drop a copy in `public/` (gitignored, regenerated by this script) so
// `vite dev`'s static file serving finds a real PDF at `/nami-shah-cv.pdf`
// too, without this, the dev server's SPA fallback would otherwise quietly
// serve `index.html` for that path since the real output normally only
// exists in `dist/` after a full build.
await writeFile(resolve("dist/nami-shah-cv.pdf"), pdf);
await writeFile(resolve("public/nami-shah-cv.pdf"), pdf);
console.log("wrote dist/nami-shah-cv.pdf and public/nami-shah-cv.pdf");
